services:
  - type: web
    name: tradingview-webhook
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
      - key: IG_API_KEY
        sync: false
      - key: IG_USERNAME
        sync: false
      - key: IG_PASSWORD
        sync: false
      - key: IG_ACCOUNT_TYPE
        value: DEMO
